<?php
/**
 * @file
 * Primary module hooks for update_logger module.
 *
 */

function update_logger_node_update(Drupal\node\NodeInterface $node)
{
  $isEnabled = \Drupal::config('update_logger.settings')->get('enable_content_log');
  if($isEnabled){
    \Drupal::logger("update_logger")->info(sprintf(
      'Node with title "%s" of type "%s" has been updated.',
      $node->getTitle(),
      $node->getType()
    ));
  }
}
